# OpenRemote v3
#
# Profile that runs the vanilla stack on https://localhost using a self-signed SSL certificate,
# with username 'admin' and password 'secret'. There is no map data available in the vanilla
# system so the map tile server will not function. Persistent data is stored in a docker
# volume called postgresql-data between restarts, simply delete this volume to reset the
# system to an empty state.
#
# Please see profile/deploy.yml for configuration details for each service.
#
version: '2.4'

services:

  proxy:
    image: openremote/proxy:${PROXY_VERSION:-2.1.2.2}
    restart: always
    depends_on:
      manager:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"

  postgresql:
    restart: always
    image: openremote/postgresql:${POSTGRESQL_VERSION:-9.6.21.0}

  keycloak:
    restart: always
    image: openremote/keycloak:${KEYCLOAK_VERSION:-12.0.1.1}
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_FRONTEND_URL:-https://localhost/auth}
      KEYCLOAK_PASSWORD: ${SETUP_ADMIN_PASSWORD:-secret}

  manager:
    restart: always
    image: openremote/manager:${MANAGER_VERSION:-latest}
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      DEV_MODE: ${DEV_MODE:-false}
      SETUP_ADMIN_PASSWORD: ${SETUP_ADMIN_PASSWORD:-secret}
