apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../kube-docker-compose.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../kube-docker-compose.yml convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: postgresql
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Amsterdam
        image: openremote/postgresql:latest
        imagePullPolicy: ""
        name: postgresql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data
status: {}
