# Automatic or manual deployment of the stack using specified docker manager image tag from docker hub
# or alternatively a git commit can be sepcified to build a custom manager image for deployment

name: Deploy

on:
  # Manually request a deploy
  workflow_dispatch:
    inputs:
      managerTag:
        description: 'Manager docker tag to pull'
      managerCommit:
        description: 'Repo commit SHA to build'
      branch:
        description: 'Branch to use (or default)'
      environment:
        description: 'Environment to use (if any)'
      host:
        description: 'Host to deploy to'
      password:
        description: 'Admin password to use'
      
        
  # Docker push webhook trigger
  repository_dispatch:
    types: [docker-push]

env:
  environment: staging

jobs:

  config:
    outputs:
      tag:
      environment: ${{ steps.set-environment.outputs.environment }}
    name: Determine config
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to DockerHub
        if: github.event.inputs.managerTag != ''
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Check manager Tag
        if: github.event.inputs.managerTag != ''
        id: manager-tag
        run: |
          docker manifest inspect openremote/manager:${{ github.event.inputs.managerTag }} > /dev/null 2> /dev/null
          echo "::set-output name=my_env::staging"
        
      - name: Check commit SHA
        if: (github.event.inputs.managerCommit != '') && (github.event.inputs.managerTag == '')
        run: echo "Secrets= ${{ toJSON(secrets) }}"
        
      - name: Set environment
        if: github.event.inputs.managerTag != ''
        id: set-environment
        run: echo "::set-output name=environment::${{ github.event.inputs.environment }}"
        
  deploy:
    needs: [config]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.config.outputs.my_env }}
    
    steps:
      
      - run: echo "Secrets= ${{ toJSON(secrets) }}"
