# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI/CD MVP

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PLATFORM: linux/amd64,linux/arm64

jobs:
  image_deployment:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist-build
      - name: build and push images
        run: |
          docker build --push --platform $PLATFORM -t openremote/deployment:mvp deployment

  image_manager:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist-build
      - name: build and push images
        run: |
          docker build --push --platform $PLATFORM -t openremote/manager:mvp manager/build/install/manager

  image_manager_swarm:
    runs-on: ubuntu-latest
    needs: [image_deployment, image_manager]

    steps:
      - uses: actions/checkout@v2
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist-build
      - name: build and push images
        run: |
          docker build --push --platform $PLATFORM -t openremote/manager-swarm:mvp -f manager/build/install/manager/swarm.Dockerfile manager/build/install/manager

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build with Gradle
        run: ./gradlew installDist
      - name: Share build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-build
          path: |
            manager/build
            deployment/build
            !dist/**/*.md
          retention-days: 1
