# This workflow handles creation of AWS member accounts by calling (.ci_cd/aws/provision_account.sh)
# You need to be a member of the CI/CD github team to use this action as it will incur costs for the organisation.
name: Provision Host

on:
  workflow_dispatch:
    inputs:
      ACCOUNT_NAME:
        description: 'New account name (lowercase simple values recommended)'
        required: false
        type: string
      PARENT_DNS_ZONE:
        description: 'Name of parent hosted domain zone in management account'
        type: string
        default: openremote.app
        required: true
      PROVISION_EFS:
        description: 'Create EFS volume called hosts-filesystem in new account'
        type: boolean
        default: true
        required: false
      HOSTED_DNS:
        description: 'Create hosted domain zone in new account'
        type: boolean
        required: false


jobs:

  provision:
    name: Provision
    runs-on: ubuntu-latest

    steps:

      - name: Check CI/CD team membership
        uses: tspascoal/get-user-teams-membership@v1
        id: checkUserMember
        with:
          username: ${{ github.actor }}
          organization: openremote
          team: CI/CD
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_FOR_READING_ORG_TEAMS }} # Personal access token used to query github (Requires scope: `read:org`)

      - name: Provision Account
        if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
        run: .ci_cd/aws/provision_account.sh "$ACCOUNT_NAME" "$PARENT_DNS_ZONE" "HOSTED_DNS" "PROVISION_EFS"
        env:
          ACCOUNT_NAME: ${{ github.event.inputs.ACCOUNT_NAME }}
          PARENT_DNS_ZONE: ${{ github.event.inputs.PARENT_DNS_ZONE }}
          HOSTED_DNS: ${{ github.event.inputs.HOSTED_DNS }}
          PROVISION_EFS: ${{ github.event.inputs.PROVISION_EFS }}
